apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-sss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-sss
  template:
    metadata:
      labels:
        app: syslog-sss
    spec:
      containers:
      - name: syslog-sss
        image: harbor.tupi.im/marketplace/syslog-sss:v0.1.0-1-stable
      imagePullSecrets:
      - name: secret-harbor