apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-legacy
  template:
    metadata:
      labels:
        app: db-legacy
    spec:
      containers:
        - name: db-legacy
          image: harbor.tupi.im/marketplace/db-legacy:0.1.0-1-stable
          ports:
            - containerPort: 5432
              protocol: TCP  

          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          - name: MYSQL_HOST
            value: "db-legacy"
          - name: MYSQL_DATABASE
            value: "tupi_web"
          - name: MYSQL_USER
            value: "ruvicha_feeder"
          - name: MYSQL_PASSWORD
            value: "123456"

          volumeMounts:
            - name: db-legacy
              mountPath: /var/lib/mysql

      imagePullSecrets:
      - name: secret-harbor

      volumes:
        - name: db-legacy
          # configMap:
          #   name: db-legacy-configmap


  volumeClaimTemplates:
    - metadata:
        name: db-legacy
      spec:
        accessModes:
          - ReadWriteOnce
        # storageClassName: "manual"
        resources:
          requests:
            storage: 1Gi
